[workspace]
members = [
    'driver',
    'base_engine',
    'frtb_engine'
]

[workspace.package]
version = "0.1.0"
authors = ["Anatoly Bugakov"]
description = "Ultima BI"
documentation = "https://example.com/"

[workspace.dependencies]
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
polars = {version = "0.24.0", features=["strings", "ndarray", "lazy", "is_in", "dtype-categorical", "serde", "csv-file", "diagonal_concat"]}
toml = "0.5"
once_cell = "1.12"