[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quant_engine = {path = "../quant_engine"}
frtb_engine = {path = "../frtb_engine"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
dotenv = "0.15"
tokio = {version = "1.17.0", features=["full"]}
clap = {version = "3.1.5", features=["cargo"]}
toml = "0.5.9"
chrono = {version = "0.4", features=["serde"]}