name: Ultima FRTB Guide

on:
  pull_request:
      paths:
        - 'frtb_userguide/**'
  push:
    branches: [master]
    paths:
      - 'frtb_userguide/**'

jobs:
  test:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y graphviz make wget
          python -m pip install ghp-import
          sudo wget https://github.com/rust-lang/mdBook/releases/download/v0.4.25/mdbook-v0.4.25-x86_64-unknown-linux-gnu.tar.gz -O - | sudo tar -xzf - -C /usr/bin/
  
      - name: Deploy docs
        run: |
          mkdir -p docs
          cd frtb_userguide
          mdbook build --dest-dir ../docs .
          cd ..
          ghp-import --no-jekyll docs
          git push -qf https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages
