name: Rust Frontend Lint Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ultima
  ECS_CLUSTER: UltimaF
  CONTAINER_NAME: test
  ECS_SERVICE: main
  

jobs:
  lint_tests:
    name: Run Clippy & Rustfmt lint tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features 

  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
       
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features 


  frontend_checks:
    name: Frontend checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        run: npm install
        working-directory: frontend
        
      - name: Typecheck
        run: npx tsc
        working-directory: frontend

      - name: Lint
        run: npm run lint
        working-directory: frontend