name: Lint Python

on:
  pull_request:
    paths:
      - 'pyultima/**'
      - '.github/workflows/lint-python.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pyultima

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyultima/requirements-lint.txt'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-lint.txt
      - name: Lint Python
        run: |
          black --check .
          blackdoc --check .
          isort --check .
          ruff .
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-24
          components: rustfmt, clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: pyultima
      - name: Lint Rust
        run: |
          cargo fmt --all -- --check
          make clippy
