name: Main App

on:
  push:
    branches: [master]

jobs:
  clippy_fmt:
    name: Clippy & Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features 

  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
       
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features 


  frontend_lint_fmt:
    name: Lint frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        run: npm install
        working-directory: frontend
        
      - name: Lint
        run: npm run lint
        working-directory: frontend

  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs:
      - clippy_fmt
      - rust_tests
      - frontend_lint_fmt

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 347605426234.dkr.ecr.eu-west-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          content: .
          push: true
          tags: 347605426234.dkr.ecr.eu-west-2.amazonaws.com/ultima:latest
