name: Test Python

on:
  pull_request:
    paths:
      - 'pyultima/**'
      - 'base_engine/**'
      - 'frtb_engine/**'
      - '.github/workflows/test-python.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: pyultima

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyultima/requirements.txt'

      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "$GITHUB_WORKSPACE/pyultima/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Allow untyped calls for older Python versions
      - name: Run mypy
        run: mypy #${{ (matrix.python-version == '3.9') && '--allow-untyped-calls' || '' }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: pyultima

      - name: Install Ultima
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          source activate
          maturin develop

      - name: Run tests and report coverage
        run: pytest --cov

      - name: Run doctests
        run: python tests/docs/run_doc_examples.py


  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyultima/requirements.txt'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: pyultima

      - name: Install Ultima
        shell: bash
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        # pip install target/wheels/ultima-*.whl
        run: |
          maturin build
          pip install --find-links=../target/wheels ultima 

      - name: Run tests
        run: pytest

