name: FRTB User Guide code snippets

on:
  pull_request:
    paths:
      - 'pyultima/**'
      - 'base_engine/**'
      - 'frtb_engine/**'
      - 'website/examples/**'
      - '.github/workflows/test-python.yaml'
      - '.github/workflows/test-python-userguide.yaml'

defaults:
  run:
    working-directory: website

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'website/examples/requirements.txt'

      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "$GITHUB_WORKSPACE/website/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y graphviz make wget

      - name: Install Ultima
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          source venv/bin/activate
          cd ../pyultima
          pip install -r requirements.txt
          maturin develop --features=CRR2

      - name: Run snippets
        shell: bash
        run: ./run-examples.sh
